# 배포용
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

sms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
  from: ${SMS_FROM}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION_STATIC}