spring:
  application:
    name: deulbull-performance-api
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  servlet:
    context-path: /api
  tomcat:
    max-swallow-size: 50MB
    max-http-form-post-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true

discord:
  booking:
    webhook: https://discord.com/api/webhooks/1447316749660848208/5F0SCRXsKyHk1A0ZzUq1VjYKCJBHI_f3h9b2TKecqbNs7ea55TmxuXkvYO_2L-oPRo9x

